export const WORDS = [
  'AGENT',
  'WORLD',
  'ABOUT',
  'HEART',
  'WATER',
  'SIXTY',
  'BOARD',
  'MONTH',
  'MUSIC',
  'PARTY',
  'PIANO',
  'MOUTH',
  'WOMAN',
  'SUGAR',
  'AMBER',
  'DREAM',
  'LAUGH',
  'TIGER',
  'EARTH',
  'MONEY',
  'WORDS',
  'SMILE',
  'LEMON',
  'SOUTH',
  'AFTER',
  'STONE',
  'THING',
  'LIGHT',
  'STORY',
  'POWER',
  'TODAY',
  'RANGE',
  'PEARL',
  'VENOM',
  'PROXY',
  'ROUND',
  'HOVER',
  'CANDY',
  'ABOVE',
  'PHONE',
  'OTHER',
  'SMART',
  'BLACK',
  'MAGIC',
  'FRUIT',
  'RADIO',
  'ROYAL',
  'HONEY',
  'FLAKE',
  'SOUND',
];

export const KEYS = [
  [
    { value: "Q", status: "neutral" },
    { value: "W", status: "neutral" },
    { value: "E", status: "neutral" },
    { value: "R", status: "neutral" },
    { value: "T", status: "neutral" },
    { value: "Y", status: "neutral" },
    { value: "U", status: "neutral" },
    { value: "I", status: "neutral" },
    { value: "O", status: "neutral" },
    { value: "P", status: "neutral" }
  ],
  [
    { value: "A", status: "neutral" },
    { value: "S", status: "neutral" },
    { value: "D", status: "neutral" },
    { value: "F", status: "neutral" },
    { value: "G", status: "neutral" },
    { value: "H", status: "neutral" },
    { value: "J", status: "neutral" },
    { value: "K", status: "neutral" },
    { value: "L", status: "neutral" }
  ],
  [
    { value: "Z", status: "neutral" },
    { value: "X", status: "neutral" },
    { value: "C", status: "neutral" },
    { value: "V", status: "neutral" },
    { value: "B", status: "neutral" },
    { value: "N", status: "neutral" },
    { value: "M", status: "neutral" }
  ]
]
